-- Generated from your live data/store.json — this is YOUR actual current
-- catalogue (including manual edits), not just the generic demo content.
-- Safe to re-run. Run this in the Supabase SQL Editor after supabase-schema.sql.

-- Categories
INSERT INTO categories (id, name, slug, description, image_url, is_active, sort_order, created_at, updated_at) VALUES ('cat-rings', 'Rings & Solitaires', 'rings', 'Sculptural silhouettes in 18K recycled gold, pavé diamonds, and bezel-set solitaires.', 'https://images.unsplash.com/photo-1605100804763-247f67b3557e?auto=format&fit=crop&q=80&w=1000', true, 1, '2026-08-18T15:14:45.433Z', '2026-08-18T15:14:45.433Z') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, slug = EXCLUDED.slug, description = EXCLUDED.description, image_url = EXCLUDED.image_url, is_active = EXCLUDED.is_active, sort_order = EXCLUDED.sort_order, updated_at = EXCLUDED.updated_at;
INSERT INTO categories (id, name, slug, description, image_url, is_active, sort_order, created_at, updated_at) VALUES ('cat-necklaces', 'Necklaces & Chains', 'necklaces', 'Heirloom herringbone chains, freshwater baroque pearl pendants, and celestial medallions.', 'https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?auto=format&fit=crop&q=80&w=1000', true, 2, '2026-08-18T15:14:45.433Z', '2026-08-18T15:14:45.433Z') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, slug = EXCLUDED.slug, description = EXCLUDED.description, image_url = EXCLUDED.image_url, is_active = EXCLUDED.is_active, sort_order = EXCLUDED.sort_order, updated_at = EXCLUDED.updated_at;
INSERT INTO categories (id, name, slug, description, image_url, is_active, sort_order, created_at, updated_at) VALUES ('cat-bracelets', 'Bracelets & Cuffs', 'bracelets', 'Chunky tennis bracelets, textured solid gold cuffs, and delicate layered chain links.', 'https://images.unsplash.com/photo-1611591475883-8a306c59b666?auto=format&fit=crop&q=80&w=1000', true, 3, '2026-08-18T15:14:45.433Z', '2026-08-18T15:14:45.433Z') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, slug = EXCLUDED.slug, description = EXCLUDED.description, image_url = EXCLUDED.image_url, is_active = EXCLUDED.is_active, sort_order = EXCLUDED.sort_order, updated_at = EXCLUDED.updated_at;
INSERT INTO categories (id, name, slug, description, image_url, is_active, sort_order, created_at, updated_at) VALUES ('cat-earrings', 'Earrings & Huggies', 'earrings', 'Modern organic hoops, pearl drops, and everyday molten huggies designed for stacking.', 'https://images.unsplash.com/photo-1630019852942-f89202989a59?auto=format&fit=crop&q=80&w=1000', true, 4, '2026-08-18T15:14:45.433Z', '2026-08-18T15:14:45.433Z') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, slug = EXCLUDED.slug, description = EXCLUDED.description, image_url = EXCLUDED.image_url, is_active = EXCLUDED.is_active, sort_order = EXCLUDED.sort_order, updated_at = EXCLUDED.updated_at;
INSERT INTO categories (id, name, slug, description, image_url, is_active, sort_order, created_at, updated_at) VALUES ('cat-pearls', 'Pearl Atelier', 'pearls', 'Luminous organic Keshi and South Sea baroque pearls curated for effortless modern luxury.', 'https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?auto=format&fit=crop&q=80&w=1000', true, 5, '2026-08-18T15:14:45.433Z', '2026-08-18T15:14:45.433Z') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, slug = EXCLUDED.slug, description = EXCLUDED.description, image_url = EXCLUDED.image_url, is_active = EXCLUDED.is_active, sort_order = EXCLUDED.sort_order, updated_at = EXCLUDED.updated_at;

-- Products
INSERT INTO products (id, name, slug, description, price, original_price, category_id, category_name, sku, stock, is_active, is_hot, is_new_drop, is_featured, restocked_at, material, color, size, weight, tags, specifications, images, created_at, updated_at) VALUES ('prod-1787074669655', 'Testing-pic', 'testing-pic', 'this is a test product', 450, NULL, 'cat-rings', 'Rings & Solitaires', 'AUR-944', 5, true, true, false, true, NULL, '18K Solid Yellow Gold', 'Yellow Gold', 'Standard', NULL, '{}', '{}'::jsonb, '[{"id":"img-1787074640712","productId":"","cloudinaryPublicId":"jewelry/gldf0vke5bkdgywramxr","secureUrl":"https://res.cloudinary.com/de8flo0fp/image/upload/v1787074634/jewelry/gldf0vke5bkdgywramxr.jpg","sortOrder":1,"isPrimary":true}]'::jsonb, '2026-08-18T17:37:49.655Z', '2026-08-18T17:37:49.655Z') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description, price = EXCLUDED.price, stock = EXCLUDED.stock, images = EXCLUDED.images, updated_at = EXCLUDED.updated_at;
INSERT INTO products (id, name, slug, description, price, original_price, category_id, category_name, sku, stock, is_active, is_hot, is_new_drop, is_featured, restocked_at, material, color, size, weight, tags, specifications, images, created_at, updated_at) VALUES ('prod-1', 'Solstice 18K Molten Signet Ring', 'solstice-18k-molten-signet-ring', 'Hand-carved in our atelier with an organic molten surface texture. Cast in solid 18K yellow gold with a bezel-set flush brilliant diamond center.', 680, 750, 'cat-rings', 'Rings & Solitaires', 'AUR-RNG-001', 7, true, true, false, true, '2026-08-10T12:00:00Z', '18K Solid Yellow Gold', 'Warm Gold', 'US 6, 7, 8 available', '6.4g', ARRAY['Best Seller','Gold','Signature','Diamond'], '{"Metal":"18 Karat Solid Gold (Hallmarked)","Stone":"0.08ct F-VS Natural Brilliant Diamond","Band Width":"3.2mm tapering to 8.5mm face","Finish":"Satin Brushed with Polished Rim","Origin":"Handcrafted in Atelier"}'::jsonb, '[{"id":"img-1-1","productId":"prod-1","cloudinaryPublicId":"aura/products/solstice-ring-1","secureUrl":"https://images.unsplash.com/photo-1605100804763-247f67b3557e?auto=format&fit=crop&q=85&w=1200","sortOrder":1,"isPrimary":true,"createdAt":"2026-08-18T15:14:45.433Z"},{"id":"img-1-2","productId":"prod-1","cloudinaryPublicId":"aura/products/solstice-ring-2","secureUrl":"https://images.unsplash.com/photo-1603561591411-07134e71a2a9?auto=format&fit=crop&q=85&w=1200","sortOrder":2,"isPrimary":false,"createdAt":"2026-08-18T15:14:45.433Z"}]'::jsonb, '2026-07-15T10:00:00Z', '2026-08-15T10:00:00Z') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description, price = EXCLUDED.price, stock = EXCLUDED.stock, images = EXCLUDED.images, updated_at = EXCLUDED.updated_at;
INSERT INTO products (id, name, slug, description, price, original_price, category_id, category_name, sku, stock, is_active, is_hot, is_new_drop, is_featured, restocked_at, material, color, size, weight, tags, specifications, images, created_at, updated_at) VALUES ('prod-2', 'Helios Baroque Pearl Lariat Necklace', 'helios-baroque-pearl-lariat-necklace', 'An asymmetrical masterpiece featuring a one-of-a-kind organic Japanese freshwater baroque pearl dangling from a delicate 18K solid gold paperclip chain.', 490, 520, 'cat-necklaces', 'Necklaces & Chains', 'AUR-NCK-002', 4, true, true, true, true, NULL, '18K Yellow Gold & AA Baroque Pearl', 'Lustrous White / Gold', '18 inch adjustable', '8.1g', ARRAY['New Drop','Pearl','Editorial','Layering'], '{"Chain":"18K Solid Gold 1.8mm Paperclip link","Pearl":"Grade AA 14-16mm Freshwater Baroque Pearl","Clasp":"Custom Atelier Lobster lock","Length":"18\" chain with 2\" drop"}'::jsonb, '[{"id":"img-2-1","productId":"prod-2","cloudinaryPublicId":"aura/products/helios-necklace-1","secureUrl":"https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?auto=format&fit=crop&q=85&w=1200","sortOrder":1,"isPrimary":true,"createdAt":"2026-08-18T15:14:45.433Z"},{"id":"img-2-2","productId":"prod-2","cloudinaryPublicId":"aura/products/helios-necklace-2","secureUrl":"https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?auto=format&fit=crop&q=85&w=1200","sortOrder":2,"isPrimary":false,"createdAt":"2026-08-18T15:14:45.433Z"}]'::jsonb, '2026-08-01T08:00:00Z', '2026-08-16T12:00:00Z') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description, price = EXCLUDED.price, stock = EXCLUDED.stock, images = EXCLUDED.images, updated_at = EXCLUDED.updated_at;
INSERT INTO products (id, name, slug, description, price, original_price, category_id, category_name, sku, stock, is_active, is_hot, is_new_drop, is_featured, restocked_at, material, color, size, weight, tags, specifications, images, created_at, updated_at) VALUES ('prod-3', 'Aethel Tennis Chain Bracelet', 'aethel-tennis-chain-bracelet', 'Timeless luxury reimagined. Four-prong set lab-created brilliant diamonds seamlessly connected along an ultra-flexible 18K white gold track with double security safety clasp.', 1250, NULL, 'cat-bracelets', 'Bracelets & Cuffs', 'AUR-BRC-003', 2, true, true, false, true, '2026-08-14T09:00:00Z', '18K White Gold & VVS Diamonds', 'White Gold / Clear', '6.75 inch', '11.2g', ARRAY['Fine Diamond','Heirloom','Restocked'], '{"Carat Weight":"2.40 ctw VVS-VS Clarity, Color E-F","Metal":"18K Solid White Gold","Width":"2.6mm","Clasp":"Integrated Box Clasp with Dual Safety Latches"}'::jsonb, '[{"id":"img-3-1","productId":"prod-3","cloudinaryPublicId":"aura/products/aethel-bracelet-1","secureUrl":"https://images.unsplash.com/photo-1611591475883-8a306c59b666?auto=format&fit=crop&q=85&w=1200","sortOrder":1,"isPrimary":true,"createdAt":"2026-08-18T15:14:45.433Z"}]'::jsonb, '2026-06-20T11:00:00Z', '2026-08-14T09:00:00Z') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description, price = EXCLUDED.price, stock = EXCLUDED.stock, images = EXCLUDED.images, updated_at = EXCLUDED.updated_at;
INSERT INTO products (id, name, slug, description, price, original_price, category_id, category_name, sku, stock, is_active, is_hot, is_new_drop, is_featured, restocked_at, material, color, size, weight, tags, specifications, images, created_at, updated_at) VALUES ('prod-4', 'Aurelia Organic Molten Gold Hoops', 'aurelia-organic-molten-gold-hoops', 'Cast in lightweight hollowed 18K gold to ensure day-to-night comfort. Features soft rippled contours that catch the light from every angle.', 340, 380, 'cat-earrings', 'Earrings & Huggies', 'AUR-EAR-004', 9, true, false, true, true, NULL, '18K Solid Gold', 'Yellow Gold', '22mm diameter', '4.8g per pair', ARRAY['Everyday','Statement','New Drop'], '{"Diameter":"22mm outer diameter","Thickness":"4.5mm at thickest wave","Post":"Hypoallergenic 18K Gold Post with Comfort Backs","Weight":"Featherlight comfortable feel"}'::jsonb, '[{"id":"img-4-1","productId":"prod-4","cloudinaryPublicId":"aura/products/aurelia-hoops-1","secureUrl":"https://images.unsplash.com/photo-1630019852942-f89202989a59?auto=format&fit=crop&q=85&w=1200","sortOrder":1,"isPrimary":true,"createdAt":"2026-08-18T15:14:45.433Z"},{"id":"img-4-2","productId":"prod-4","cloudinaryPublicId":"aura/products/aurelia-hoops-2","secureUrl":"https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?auto=format&fit=crop&q=85&w=1200","sortOrder":2,"isPrimary":false,"createdAt":"2026-08-18T15:14:45.433Z"}]'::jsonb, '2026-08-05T14:00:00Z', '2026-08-17T09:00:00Z') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description, price = EXCLUDED.price, stock = EXCLUDED.stock, images = EXCLUDED.images, updated_at = EXCLUDED.updated_at;
INSERT INTO products (id, name, slug, description, price, original_price, category_id, category_name, sku, stock, is_active, is_hot, is_new_drop, is_featured, restocked_at, material, color, size, weight, tags, specifications, images, created_at, updated_at) VALUES ('prod-5', 'Siren Keshi Pearl Strand Choker', 'siren-keshi-pearl-strand-choker', 'Individually hand-knotted on pure silk thread with rare petal-shaped natural Keshi pearls. Secured with an engraved 18K gold ball clasp.', 560, NULL, 'cat-pearls', 'Pearl Atelier', 'AUR-PRL-005', 0, true, true, false, true, NULL, 'Natural Keshi Pearls & 18K Gold', 'Iridescent Pearl Ivory', '15.5 inch choker', '14.5g', '{}', '{"Pearl Grade":"AAA Natural Iridescent Luster","Thread":"Japanese White Silk (Hand-Knotted)","Clasp":"18K Solid Gold Satin Round Lock","Care":"Avoid direct perfumes and store in silk pouch"}'::jsonb, '[{"id":"img-5-1","productId":"prod-5","cloudinaryPublicId":"aura/products/siren-keshi-1","secureUrl":"https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?auto=format&fit=crop&q=85&w=1200","sortOrder":1,"isPrimary":true}]'::jsonb, '2026-05-10T12:00:00Z', '2026-08-18T15:42:08.150Z') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description, price = EXCLUDED.price, stock = EXCLUDED.stock, images = EXCLUDED.images, updated_at = EXCLUDED.updated_at;
INSERT INTO products (id, name, slug, description, price, original_price, category_id, category_name, sku, stock, is_active, is_hot, is_new_drop, is_featured, restocked_at, material, color, size, weight, tags, specifications, images, created_at, updated_at) VALUES ('prod-6', 'Celeste Sapphire Celestial Ring', 'celeste-sapphire-celestial-ring', 'Deep royal blue Australian oval sapphire flanked by two tapered baguette diamonds in an architectural 18K yellow gold knife-edge band.', 890, 980, 'cat-rings', 'Rings & Solitaires', 'AUR-RNG-006', 5, true, false, true, true, '2026-08-16T15:30:00Z', '18K Yellow Gold & Natural Sapphire', 'Deep Midnight Blue / Gold', 'US 5, 6, 7', '5.2g', ARRAY['Gemstone','Sapphire','New Drop','Restocked'], '{"Center Stone":"1.20ct Natural Untreated Royal Blue Sapphire","Side Diamonds":"0.18ctw Tapered VS Baguettes","Profile":"Low profile comfort prong setting","Metal":"18K Yellow Gold"}'::jsonb, '[{"id":"img-6-1","productId":"prod-6","cloudinaryPublicId":"aura/products/celeste-sapphire-1","secureUrl":"https://images.unsplash.com/photo-1603561591411-07134e71a2a9?auto=format&fit=crop&q=85&w=1200","sortOrder":1,"isPrimary":true,"createdAt":"2026-08-18T15:14:45.433Z"}]'::jsonb, '2026-08-08T11:00:00Z', '2026-08-16T15:30:00Z') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description, price = EXCLUDED.price, stock = EXCLUDED.stock, images = EXCLUDED.images, updated_at = EXCLUDED.updated_at;
INSERT INTO products (id, name, slug, description, price, original_price, category_id, category_name, sku, stock, is_active, is_hot, is_new_drop, is_featured, restocked_at, material, color, size, weight, tags, specifications, images, created_at, updated_at) VALUES ('prod-7', 'Vermeil Sculptural Chunky Cuff', 'vermeil-sculptural-chunky-cuff', 'Architectural statement piece inspired by Brutalist bronze sculptures. Ergonomically contoured to sit flush against the wrist.', 420, NULL, 'cat-bracelets', 'Bracelets & Cuffs', 'AUR-BRC-007', 8, true, false, false, false, '2026-08-11T10:00:00Z', 'Heavy 18K Gold Vermeil over Sterling Silver', 'Polished Gold', 'Medium (Fits wrists 6.0" - 7.0")', '28.0g', ARRAY['Sculptural','Statement','Cuff'], '{"Plating":"5 Microns 18K Solid Gold over 925 Silver","Gap Width":"1.2 inches for easy on/off wear","Finish":"Mirror Polish Exterior with Brushed Inner"}'::jsonb, '[{"id":"img-7-1","productId":"prod-7","cloudinaryPublicId":"aura/products/vermeil-cuff-1","secureUrl":"https://images.unsplash.com/photo-1599643477877-530eb83abc8e?auto=format&fit=crop&q=85&w=1200","sortOrder":1,"isPrimary":true,"createdAt":"2026-08-18T15:14:45.433Z"}]'::jsonb, '2026-07-20T09:00:00Z', '2026-08-11T10:00:00Z') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description, price = EXCLUDED.price, stock = EXCLUDED.stock, images = EXCLUDED.images, updated_at = EXCLUDED.updated_at;
INSERT INTO products (id, name, slug, description, price, original_price, category_id, category_name, sku, stock, is_active, is_hot, is_new_drop, is_featured, restocked_at, material, color, size, weight, tags, specifications, images, created_at, updated_at) VALUES ('prod-8', 'Astrid Emerald Cut Pendant Chain', 'astrid-emerald-cut-pendant-chain', 'Vintage-inspired Colombian emerald green quartz stone framed by micro-pavé accents on an Italian cable chain.', 360, 410, 'cat-necklaces', 'Necklaces & Chains', 'AUR-NCK-008', 6, true, true, false, true, NULL, '18K Yellow Gold Vermeil', 'Emerald Green / Gold', '16-18 inch adjustable', '5.5g', ARRAY['Emerald','Pendant','Vintage'], '{"Stone":"2.0ct Emerald-cut Fine Hydrothermal Quartz","Chain Style":"Diamond-cut Italian cable chain","Pendant Dimensions":"12mm x 9mm"}'::jsonb, '[{"id":"img-8-1","productId":"prod-8","cloudinaryPublicId":"aura/products/astrid-emerald-1","secureUrl":"https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?auto=format&fit=crop&q=85&w=1200","sortOrder":1,"isPrimary":true,"createdAt":"2026-08-18T15:14:45.433Z"}]'::jsonb, '2026-07-28T14:00:00Z', '2026-08-15T08:00:00Z') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description, price = EXCLUDED.price, stock = EXCLUDED.stock, images = EXCLUDED.images, updated_at = EXCLUDED.updated_at;

-- Offers
INSERT INTO offers (id, title, tagline, description, code, discount_type, discount_value, image_url, is_active, start_date, end_date, associated_product_ids, associated_category_ids, sort_order, created_at, updated_at) VALUES ('offer-1', 'Maison Spring Atelier Special', 'Complimentary 18K Polish Cloth & Silk Travel Case with every order', 'Take 15% off any curated Solid Gold and Pearl combination when you order this week.', 'ATELIER15', 'PERCENTAGE', 15, 'https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?auto=format&fit=crop&q=80&w=1200', true, '2026-08-01T00:00:00Z', '2026-09-30T23:59:59Z', ARRAY['prod-1','prod-2','prod-4'], ARRAY['cat-rings','cat-necklaces','cat-pearls'], 1, '2026-08-18T15:14:45.434Z', '2026-08-18T15:14:45.434Z') ON CONFLICT (id) DO UPDATE SET title = EXCLUDED.title, description = EXCLUDED.description, updated_at = EXCLUDED.updated_at;

-- Site settings (single default row)
INSERT INTO site_settings (id, store_name, tagline, logo_url, instagram_handle, custom_order_message_template, currency_symbol, contact_email, contact_phone, announcement_text, announcement_enabled, announcement_link, hero_headline, hero_subhead, hero_image_url, hero_cta_text, hero_cta_link, default_seo_title, default_seo_description, default_seo_keywords, about_text, atelier_address, hero_eyebrow_text, hero_current_drop_label, hero_current_drop_text, hero_secondary_cta_text, hero_inquiry_card_title, hero_inquiry_card_subtitle, hero_inquiry_card_text, categories_heading, categories_show_all_text, categories_all_pill_label, offers_eyebrow_text, offers_code_label, footer_philosophy_eyebrow, footer_collections_heading, footer_ordering_heading, footer_ordering_text, footer_bottom_tagline) VALUES ('default', 'AURA Fine Jewelry', 'Handcrafted Solid Gold, Pearls & Precious Stones', '', 'aurafinejewelry', 'Hi AURA Atelier, I''m interested in ordering the {product_name} (SKU: {product_sku}, Price: NPR {product_price}). URL: {product_url}', 'NPR ', 'concierge@aurajewelry.com', '+1 (555) 234-8900', 'Complimentary insured worldwide shipping on all atelier drops | DM on Instagram for bespoke sizing', true, '/offers', 'Sculptural Elegance for the Modern Collector', 'Ethically crafted in 18K recycled solid gold and handpicked baroque pearls. Browse our curated catalogue and claim your piece directly via Instagram.', 'https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?auto=format&fit=crop&q=85&w=1600', 'Explore New Drop', '#catalog', 'AURA Fine Jewelry | Pinterest-Inspired Atelier', 'Browse the handcrafted luxury jewelry catalogue from AURA. Order seamlessly via Instagram messaging.', 'fine jewelry, 18k gold, natural pearls, engagement rings, handcrafted jewelry', 'AURA Atelier was founded on the philosophy that fine jewelry should be intimate, tactile, and sculpturally distinct. Each item is produced in limited micro-batches in our studio.', 'SoHo Design District, New York & Paris', 'Editorial 2026', 'Current Atelier Drop', 'Celestial 18K Solid Gold & Baroque Series', 'New Arrivals', 'Instagram Inquiry', 'Atelier Concierge', 'Select any piece from our catalogue to message us directly for bespoke ring sizing and insured global dispatch.', 'Curated Categories', 'Show All Curations', 'All Atelier', 'Limited Seasonal Atelier Event', 'Mention code:', 'Atelier Philosophy', 'Collections', 'Instagram Ordering', 'We provide tailored bespoke sizing, custom diamond settings, and insured global delivery. Inquire directly via Instagram messaging.', 'Curated in Florence & New York') ON CONFLICT (id) DO UPDATE SET store_name = EXCLUDED.store_name, tagline = EXCLUDED.tagline, updated_at = NOW();

-- Customer inquiries
INSERT INTO customer_inquiries (id, product_id, product_name, product_sku, product_price, product_slug, product_image, instagram_handle, customer_note, status, created_at) VALUES ('inq-1', 'prod-1', 'Solstice 18K Molten Signet Ring', 'AUR-RNG-001', 680, 'solstice-18k-molten-signet-ring', 'https://images.unsplash.com/photo-1605100804763-247f67b3557e?auto=format&fit=crop&q=85&w=800', 'aurafinejewelry', 'Customer initiated Instagram inquiry for Size 7.', 'PENDING', '2026-08-18T10:14:45.435Z') ON CONFLICT (id) DO NOTHING;

-- Media assets (Cloudinary uploads you already made)
INSERT INTO media_assets (id, public_id, secure_url, format, width, height, created_at) VALUES ('media-1787074640704', 'jewelry/gldf0vke5bkdgywramxr', 'https://res.cloudinary.com/de8flo0fp/image/upload/v1787074634/jewelry/gldf0vke5bkdgywramxr.jpg', 'jpg', 1600, 800, '2026-08-18T17:37:20.704Z') ON CONFLICT (id) DO NOTHING;
INSERT INTO media_assets (id, public_id, secure_url, format, width, height, created_at) VALUES ('media-1787074367231', 'jewelry/pnu17pmkvrhirqo3mm0w', 'https://res.cloudinary.com/de8flo0fp/image/upload/v1787074361/jewelry/pnu17pmkvrhirqo3mm0w.png', 'png', 1, 1, '2026-08-18T17:32:47.231Z') ON CONFLICT (id) DO NOTHING;
INSERT INTO media_assets (id, public_id, secure_url, format, width, height, created_at) VALUES ('media-1787074276686', 'jewelry/xujyjhzibjttunosbsif', 'https://res.cloudinary.com/de8flo0fp/image/upload/v1787074270/jewelry/xujyjhzibjttunosbsif.png', 'png', 1, 1, '2026-08-18T17:31:16.686Z') ON CONFLICT (id) DO NOTHING;
INSERT INTO media_assets (id, public_id, secure_url, format, width, height, created_at) VALUES ('media-1787074235316', 'jewelry/ll3few0igfygqrgadozu', 'https://res.cloudinary.com/de8flo0fp/image/upload/v1787074229/jewelry/ll3few0igfygqrgadozu.png', 'png', 1, 1, '2026-08-18T17:30:35.316Z') ON CONFLICT (id) DO NOTHING;
INSERT INTO media_assets (id, public_id, secure_url, format, width, height, created_at) VALUES ('media-1787073755778', 'jewelry/bai8n0ng4e5yjjdmjn4p', 'https://res.cloudinary.com/de8flo0fp/image/upload/v1787073750/jewelry/bai8n0ng4e5yjjdmjn4p.jpg', 'jpg', 1600, 800, '2026-08-18T17:22:35.778Z') ON CONFLICT (id) DO NOTHING;
INSERT INTO media_assets (id, public_id, secure_url, format, width, height, created_at) VALUES ('media-1787073520168', 'jewelry/qi9wsupbluekoqayilyy', 'https://res.cloudinary.com/de8flo0fp/image/upload/v1787073514/jewelry/qi9wsupbluekoqayilyy.jpg', 'jpg', 1600, 800, '2026-08-18T17:18:40.168Z') ON CONFLICT (id) DO NOTHING;
INSERT INTO media_assets (id, public_id, secure_url, format, width, height, created_at) VALUES ('media-1787073028363', 'jewelry/dln3v9o6i8eoffu4mrqs', 'https://res.cloudinary.com/de8flo0fp/image/upload/v1787073023/jewelry/dln3v9o6i8eoffu4mrqs.jpg', 'jpg', 1600, 800, '2026-08-18T17:10:28.363Z') ON CONFLICT (id) DO NOTHING;
INSERT INTO media_assets (id, public_id, secure_url, format, width, height, created_at) VALUES ('media-1787072046095', 'jewelry/edamtezvwpmcghxvsewb', 'https://res.cloudinary.com/de8flo0fp/image/upload/v1787072040/jewelry/edamtezvwpmcghxvsewb.jpg', 'jpg', 1600, 800, '2026-08-18T16:54:06.095Z') ON CONFLICT (id) DO NOTHING;
INSERT INTO media_assets (id, public_id, secure_url, format, width, height, created_at) VALUES ('media-1787072001934', 'jewelry/m8nhm9fwxf9iqbnrlzha', 'https://res.cloudinary.com/de8flo0fp/image/upload/v1787071996/jewelry/m8nhm9fwxf9iqbnrlzha.png', 'png', 1, 1, '2026-08-18T16:53:21.934Z') ON CONFLICT (id) DO NOTHING;

-- Currency switched to Nepalese Rupees, and brand renamed to mini2k — force
-- an update in case the row above already existed from an earlier seed run
-- (the INSERT's ON CONFLICT clause doesn't touch these columns).
UPDATE site_settings SET
  store_name = 'mini2k',
  instagram_handle = 'mini2k.np',
  contact_email = 'concierge@mini2k.com',
  default_seo_title = 'mini2k',
  about_text = 'mini2k was founded on the philosophy that fine jewelry should be intimate, tactile, and sculpturally distinct. Each item is produced in limited micro-batches in our studio.',
  currency_symbol = 'NPR ',
  custom_order_message_template = 'Hi mini2k, I''m interested in ordering the {product_name} (SKU: {product_sku}, Price: NPR {product_price}). URL: {product_url}'
WHERE id = 'default';
